"""Validate Markdown specs and generate the Python contracts they define."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPECS = ROOT / "specs"
FENCE = re.compile(r"```json\s*(.*?)\s*```", re.DOTALL)
TYPE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*(?:\[[A-Za-z0-9_ |]+\]| \| None)?$")


def contract_for(spec_path: Path) -> dict:
    match = FENCE.search(spec_path.read_text())
    if not match:
        raise ValueError(f"{spec_path}: missing a ```json contract block")
    try:
        contract = json.loads(match.group(1))
    except json.JSONDecodeError as error:
        raise ValueError(f"{spec_path}: invalid contract JSON: {error}") from error
    if not isinstance(contract.get("models"), list) or not contract["models"]:
        raise ValueError(f"{spec_path}: contract must contain at least one model")
    return contract


def check() -> int:
    errors: list[str] = []
    paths = sorted(SPECS.glob("*.md"))
    for path in paths:
        text = path.read_text()
        if not text.startswith("# "):
            errors.append(f"{path}: missing a top-level title")
        if path.name.startswith("000-"):
            continue
        for heading in ("## User story", "## Rules", "## Acceptance criteria"):
            if heading not in text:
                errors.append(f"{path}: missing {heading}")
        try:
            contract = contract_for(path)
            for model in contract["models"]:
                if not model.get("name") or not model.get("fields"):
                    errors.append(f"{path}: every model needs a name and fields")
                for field in model.get("fields", []):
                    if not field.get("name") or not TYPE.fullmatch(field.get("type", "")):
                        errors.append(f"{path}: invalid field definition {field}")
        except ValueError as error:
            errors.append(str(error))
    if errors:
        print("Spec check failed:\n" + "\n".join(f"- {error}" for error in errors))
        return 1
    print(f"Checked {len(paths)} Markdown specs")
    return 0


def generate() -> int:
    for spec_path in sorted(SPECS.glob("*.md")):
        if spec_path.name.startswith("000-"):
            continue
        contract = contract_for(spec_path)
        destination = ROOT / contract["module"]
        blocks = [
            "# Generated by `python scripts/spec.py generate`. Do not edit.",
            "",
            "from dataclasses import dataclass",
            "",
        ]
        for model in contract["models"]:
            blocks.extend(["@dataclass(frozen=True)", f"class {model['name']}:"])
            for field in model["fields"]:
                default = f" = {field['default']}" if "default" in field else ""
                blocks.append(f"    {field['name']}: {field['type']}{default}")
            blocks.extend(["", ""])
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text("\n".join(blocks).rstrip() + "\n")
        print(f"Generated {destination.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("check", "generate", "all"))
    args = parser.parse_args()
    if args.command == "check":
        return check()
    if args.command == "generate":
        return generate()
    return check() or generate()


if __name__ == "__main__":
    raise SystemExit(main())
